Add validation for affects without affectedness
RedHatProductSecurity/osidb pull request #126
Opened 2023-01-25 22:30 UTC by costaconrado

This PR adds validation for affects in exceptional state without affectedness.

Closes OSIDB-361.

2023-01-26 19:30 UTC, costaconrado commented on osidb/models.py
> +        (Only accepts WONTFIX and DEFER as resolution, validated by other validation)
I have implemented as an alert following the same logic of SMF2 but I do agree, and any legacy data without it should be imported without validation errors any way.
I will submit a refactoring on that.

2023-01-27 07:30 UTC, osoukup requested changes
The implemented validations are quite different from the corresponding SFM2 ones. The most important thing is that for two special combinations **None:defer** and **None:wontfix** we do not raise exception but only create a warning alert.

Let me explain the reason. It ancient ProdSec ages **defer** and **wontfix** were also affectedness values but later they became resolutions - like **affected:wontfix**. To unify the status of the data we performed a data migration - eg. **defer:None** became **None:defer**. As we however could not programmatically decide whether to choose **affected:defer** of **new:defer** we have to leave the affectedness empty even though it is a required attribute - and for new affects it still should be required. However as it was a lot of but often very old data no one will reanalyze it just to set the correct affectedness. However if we make the error blocking no one can do any modifications to this old data which is also not desired. Therefore we ended up where we are.

2023-01-27 07:33 UTC, osoukup commented
One more note. Wouldn't it be enough to have the validation on the affect? The affectedness or resolution should be changed through the affect API only so it seems to me that the flaw validation is duplicite.

2023-01-27 11:09 UTC, Elkasitu commented on osidb/models.py
> +        (Only accepts WONTFIX and DEFER as resolution, validated by other validation)
pinging @osoukup to get his opinion just in case

2023-01-27 12:10 UTC, osoukup commented on osidb/models.py
> +        (Only accepts WONTFIX and DEFER as resolution, validated by other validation)
Affectedness should be mandatory for the new affects and for the old ones too except the two special cases where we should just warn. I put the detailed description below.

2023-01-27 12:20 UTC, costaconrado commented
Thank you for the explanation, I have submitted the changes I believe that reflects it, please take a look.

2023-01-27 13:25 UTC, Elkasitu approved these changes
Apologies for the extra work, thankfully @osoukup caught my mistakes 😄

2023-01-27 13:39 UTC, osoukup approved these changes
LGTM now. Thank you for incorporating my feedback!

2023-01-27 13:39 UTC, osoukup commented on osidb/models.py
> +                "a exceptional state having no affectedness.",
nitpick: an exceptional

2023-01-27 13:57 UTC, merged