Add validation on flaw title format
RedHatProductSecurity/osidb pull request #142
Opened 2023-02-07 14:48 UTC by costaconrado

This PR adds validation on flaw title format.

This PR enforces all flaws to have a title formatted in the following pattern: `[EMBARGOED] [CVE IDs [...]] <component name>: <description of vulnerability nature>`.
In order to achieve that some tests were edited to send the correct format.

Closes OSIDB-331.

2023-02-08 07:24 UTC, osoukup approved these changes
LGTM.

I have a small complain that I like the SFM2 error messages a bit more. You are correct that anything missing (or not recognized) means an invalid title. However it seems to me that better is to be more specific. In the first case really mention that the component is missing (or was not recognized) and in the second one that the description is missing/empty.

Anyway in the future when we get rid of Bugzilla there will be no more need to have EMBARGOED in the title same as the list of CVEs and the component should become an ordinary attribute so this should be all temporary. Then it would be enough to just check non-emptiness.

2023-02-08 09:39 UTC, Elkasitu requested changes
I don't think this should be a validation at all, I have already expressed why but the tl;dr is that whenever we enable writing directly to OSIDB (which is presumably coming soon since we've done the bbsync work) we'll have to remove this validation because with it clients can't create proper titles (e.g. "Buffer overflow in libcurl/curl")

We can check that the title conforms to the bugzilla "spec" by performing the check in bzimport

2023-02-08 12:46 UTC, osoukup commented
> I don't think this should be a validation at all, I have already expressed why but the tl;dr is that whenever we enable writing directly to OSIDB (which is presumably coming soon since we've done the bbsync work) we'll have to remove this validation because with it clients can't create proper titles (e.g. "Buffer overflow in libcurl/curl")
> 
> We can check that the title conforms to the bugzilla "spec" by performing the check in bzimport

I agree that for the clients it is an unnecessary burden. And I agree that it is not future proof. You are maybe right and we should reconsider it. It would mean two things. The bzimport collector has to decompose the Bugzilla summary and strip some unneeded parts away (not sure what to do in the case they are not valid) and the BBSync would compose the Bugzilla summary from the title, CVE(s), embargo status, and the component. This would require adding the component as the model attribute. Maybe @costaconrado hold on this and let us discuss it.

2023-03-16 09:31 UTC, osoukup commented
@costaconrado this can be closed in favor of https://github.com/RedHatProductSecurity/osidb/pull/163

2023-04-20 07:57 UTC, closed without merging