Create CVSS model
RedHatProductSecurity/osidb pull request #239
Opened 2023-06-16 10:51 UTC by tciernik

Closes OSIDB-377

2023-06-20 13:29 UTC, osoukup requested changes
This is very good and I think close to be done but I am rising a few suggestions and questions. I am opened to a different opinion however.

2023-06-20 13:29 UTC, osoukup commented on osidb/models.py
> +    def create_cvss(flaw, affect, vector, issuer, version, **extra_fields):
Based on my comment to the vector bellow I think this should actually be rather maybe `create_or_update` (the `_cvss` part in the name is unnecessary as this is all CVSS) and by used to potentially update the vector.

2023-06-20 13:29 UTC, osoukup commented on osidb/models.py
> +    def create_cvss(flaw, affect, vector, issuer, version, **extra_fields):
I am not sure what are the `extra_fields` but if this is eventually used for the update too we should account for them appropriately whatever it means.

2023-06-20 13:29 UTC, osoukup commented on osidb/models.py
> +    )
I would deal with the relations in the child classes. The reason is that a single CVSS record cannot relate to a flaw and an affect at the same time. It is always one or the other. I would simply create a child classes `FlawCVSS` and `AffectCVSS` which would account for the relations so those relations would be removed from the base `CVSS`.

2023-06-20 13:29 UTC, osoukup commented on osidb/models.py
> +        default=CVSSVersion.VERSION3,
I am not sure the default value should be here. True that currently the CVSSv3 is the one we use the most but I think that the version should be always explicitly specified and not defaulted.

2023-06-20 13:29 UTC, osoukup commented on osidb/models.py
> -
All these black line removals are unrelated to the task so should be either done in an independent commit with an explanation why we remove them or not done at all.

2023-06-20 13:29 UTC, osoukup commented on osidb/tests/factories.py
> +    CVSS,
This is not alphabetically ordered.

2023-06-20 13:29 UTC, osoukup commented on osidb/tests/factories.py
> +    vector = "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:N"
It would be nice to have here at least a few choices.

2023-07-04 14:17 UTC, JakubFrejlach commented
Closed in favour of https://github.com/RedHatProductSecurity/osidb/pull/271

2023-07-04 14:17 UTC, closed without merging