Command to sync specific CVE manually
RedHatProductSecurity/osidb pull request #368
Opened 2023-11-01 15:55 UTC by skontar

2023-11-01 16:21 UTC, osoukup approved these changes
LGTM

2023-11-02 08:01 UTC, Elkasitu requested changes
See relevant JIRA ticket

2023-11-07 14:30 UTC, skontar commented
`STATIC` variables were added to allow running command locally.

2023-11-07 14:36 UTC, skontar commented
We can now call `python manage.py syncflaws  CVE-2023-3972`. This works because CVEs are aliases in BZ, so it is accepted instead of id.

2023-11-07 15:47 UTC, osoukup approved these changes
LGTM

2023-11-08 10:03 UTC, skontar commented
I am running:
```bash
$ . .env; export OSIDB_DB_PASSWORD BZIMPORT_BZ_API_KEY; OSIDB_DB_PORT=$( podman port osidb-data | awk -F':' '/5432/ { print $2 }'); python manage.py syncflaws CVE-2023-3972 --settings=config.settings_shell
```
Without STATIC part, I get:
```
django.core.exceptions.ImproperlyConfigured: Empty static prefix not permitted
```

2023-11-09 11:42 UTC, skontar commented
@Elkasitu I did a rebase, but I am not sure if it is correct. Can you please check?

2023-11-09 15:36 UTC, Elkasitu commented
@skontar try doing `git pull --rebase origin master` and changing the commit message, it looks like a merge commit

2023-11-09 15:43 UTC, osoukup commented
If this needs reconfirmation, still LGTM

2023-11-10 09:09 UTC, closed without merging

2023-11-10 09:22 UTC, skontar commented
See https://github.com/RedHatProductSecurity/osidb/pull/378