Sync keywords among repos
RedHatProductSecurity/osidb pull request #443
Opened 2024-02-08 13:15 UTC by jobselko

This PR moves and updates NVD keywords to keep all three repos consistent (Assembler, OSIDB, guitoutils).

Related to OSIDB-2107

2024-02-08 13:17 UTC, jobselko commented
FYI, nothing was removed, only alphabetically sorted.

2024-02-08 13:25 UTC, osoukup requested changes

2024-02-08 13:44 UTC, jobselko commented on collectors/nvd/keywords.py
> +    r"WordPress.*plugin",
This list is the exact copy of `guitoutils` and `Assembler` (see links in Jira). My aim is to keep it consistent everywhere to be able to find out what has changed quickly.

I could change it to sth like `[..., 'WPS Office', r'WordPress.*plugin', 'Zikula Application Framework', ...]`, but then I would have to do it everywhere.

2024-02-08 13:53 UTC, osoukup commented on collectors/nvd/keywords.py
> +    r"WordPress.*plugin",
I have exactly the same aim. When I am looking for what has changed, I proceed alphabetically. Just try this
```
sorted(["def", r"abc"])
```

2024-02-08 13:56 UTC, jobselko commented on collectors/nvd/keywords.py
> +    r"WordPress.*plugin",
Yeah, I am just trying that :). The output is ['abc', 'def']. Note that **r** is removed.

2024-02-08 13:57 UTC, jobselko commented on collectors/nvd/keywords.py
> +    r"WordPress.*plugin",
But adding **r** to 30 items should not be a problem.

2024-02-08 14:02 UTC, jobselko commented on collectors/nvd/keywords.py
> +    r"WordPress.*plugin",
Is it your last word that I should do it? :)

2024-02-08 14:08 UTC, osoukup commented on collectors/nvd/keywords.py
> +    r"WordPress.*plugin",
My word is that the list should be idempotent against Python sorting unless you convince me that there is valid and good reason not to it this way.

2024-02-08 14:14 UTC, jobselko commented on collectors/nvd/keywords.py
> +    r"WordPress.*plugin",
Agree with you, I will do it.

2024-02-09 05:42 UTC, osoukup approved these changes
LGTM

2024-02-09 09:43 UTC, merged