Fix rendering of git commit id on the main page
RedHatProductSecurity/osidb pull request #463
Opened 2024-03-06 12:48 UTC by jobselko

This PR is a follow-up to #410 and enables the correct rendering of git commit id on the main page.

Closes OSIDB-2235

2024-03-06 17:12 UTC, jobselko commented on osidb/renderers.py
> -        data["revision"] = os.getenv("OPENSHIFT_BUILD_COMMIT") or "unknown"
@JimFuller-RedHat Is it safe to remove this, or is there any other reason for having it?

2024-03-08 07:38 UTC, osoukup requested changes
The addition is correct, the removal is not.

2024-03-08 07:38 UTC, osoukup commented on osidb/renderers.py
> -        data["revision"] = os.getenv("OPENSHIFT_BUILD_COMMIT") or "unknown"
@jobselko we do not want to remove this. Have a look at https://osidb.prodsec.redhat.com/osidb/api/v1/flaws/CVE-2023-36053?include_fields=x

2024-03-08 09:34 UTC, jobselko commented on osidb/renderers.py
> -        data["revision"] = os.getenv("OPENSHIFT_BUILD_COMMIT") or "unknown"
Thanks, I thought it would have some meaning :)

2024-03-11 11:20 UTC, osoukup approved these changes
LGTM

2024-03-11 11:33 UTC, merged