Introduce CVSS v4 in OSIDB
RedHatProductSecurity/osidb pull request #468
Opened 2024-03-11 12:24 UTC by jobselko

This PR introduces CVSS v4 in OSIDB. The NVD collector was not updated because NVD does not support v4 yet.

Related to OSIDB-528

2024-03-11 12:57 UTC, osoukup requested changes
I see that the Bugzilla integration is being extended/updated but I do not see any integration test. We are quite constantly having bugs in the integration so we should be more mindful about testing it.

2024-03-12 15:53 UTC, jobselko commented
@osoukup I tested the code against the BZ stage, even though this change only extends the `CVSSVersion` enum by a new string and nothing more. I was able to test it only manually via curl. For some reason, none of the integration tests worked for me. I think it would be better to discuss it tomorrow.

2024-03-13 12:48 UTC, osoukup commented
> @osoukup I tested the code against the BZ stage, even though this change only extends the `CVSSVersion` enum by a new string and nothing more. I was able to test it only manually via curl. For some reason, none of the integration tests worked for me. I think it would be better to discuss it tomorrow.

Stating that only the enum is being changed is an underrating of this PR. I see both BBSync and bzimport are being modified too. Based on a number of recent negative experience I would like us to be more mindful about the integration testing.

2024-03-14 11:41 UTC, osoukup approved these changes
Good job. LGTM

And based on our previous troubles I am introducing this change
https://github.com/RedHatProductSecurity/osidb/pull/474

2024-03-14 11:41 UTC, osoukup commented on apps/bbsync/srtnotes.py
> +
nitpick: should be in the previous commit (but you can leave it as it is)

2024-03-14 12:52 UTC, merged