OSIDB-2269: implement history on Flaw, Affects and FlawMeta
RedHatProductSecurity/osidb pull request #483
Opened 2024-03-25 14:03 UTC by JimFuller-RedHat

2024-03-26 21:22 UTC, JimFuller-RedHat commented
got a weird django migration check error

_/home/jfuller/src/osidb/venv/lib64/python3.9/site-packages/django/core/management/commands/makemigrations.py:105: RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': could not translate host name "postgres" to address: Name or service not known_

will check when I come back

2024-04-03 12:50 UTC, osoukup reviewed
I am submitting a partial review. Will continue tomorrow.

2024-04-03 12:50 UTC, osoukup commented on osidb/migrations/0123_history_audit.py
> +    ]
I think I will trust that this migration does all it should :smile: this is above my knowledge.

2024-04-03 12:50 UTC, osoukup commented on osidb/models.py
> +    exclude="local_updated_dt,meta_attr,_alerts",
The `_alerts` attribute will unfortunately soon cause some conflict as Daniel is just reworking it into a proper model. That future model can also be excluded from the history as we can recreate the alerts if needed.

2024-04-03 12:50 UTC, osoukup commented on osidb/models.py
> +)
`FlawMeta` is a relic model and a subject for a removal (with the next major release). All of its parts were already migrated into other places (like `FlawReference` etc.). You can simply exclude it from the audit.

2024-04-04 11:26 UTC, osoukup reviewed
Submitting the second part of my review.

2024-04-04 11:26 UTC, osoukup commented on osidb/serializer.py
> +            + HistoryMixinSerializer.Meta.fields
nitpick: I am sure that it is not always possible but when it is I would prefer ordering the list-like structures alphabetically so a human can easily see what is there and what is not

2024-04-04 11:26 UTC, osoukup commented on osidb/tests/test_audit.py
> +        Flaw.objects.all().delete()
I wonder why the flaws are deleted first. Looking at the event count later it seems that it generates no event so I guess it has no effect - which is what I would assume at the beginning of a test (no flaws present).

2024-04-04 11:28 UTC, osoukup requested changes
So overall this LGTM with one exception which is `FlawMeta`. It should be removed soon so we should not add more code using it so the removal is not getting complicated. Otherwise a lot of great work done!

2024-04-04 11:49 UTC, JakubFrejlach reviewed
I have same smaller remarks or question but otherwise looking good!

2024-04-04 11:49 UTC, JakubFrejlach commented on osidb/serializer.py
> +            include_history_param = request.query_params.get("include_history")
Suggestion: You might want to describe this query parameter in OpenAPI schema the same way as we did with the `include_fields` or `exclude_fields`, see api_views.py for that.

2024-04-04 11:49 UTC, JakubFrejlach commented on osidb/serializer.py
> +            self.fields.pop("history", None)
Putting basically `include_fields=<anything>` will surface the history?

2024-04-04 11:49 UTC, JakubFrejlach approved these changes

2024-06-12 07:10 UTC, osoukup approved these changes
Looks great!

2024-06-12 07:10 UTC, osoukup commented on osidb/api_views.py
> +    permission_classes = [IsAuthenticatedOrReadOnly]
I have a question (maybe I already asked in the past). Is the audit/history safeguarded by the same ACLs? I do not understand this part well but it either should be or the audit would need to be only for the privileged users not to expose anything above the ACLs.

2024-06-12 07:10 UTC, osoukup commented on osidb/api_views.py
> +    permission_classes = [IsAuthenticatedOrReadOnly]
I see below in the migration that the audit table has `acl_read`/`acl_write` so I think my question is probably unnecessary and it seem everything is as it should be.

2024-06-12 07:14 UTC, JimFuller-RedHat commented on docs/developer/DEVELOP.md
> +ALTER TABLE osidb_flawmeta DISABLE TRIGGER ALL;
ah I missed that, thx

2024-06-12 07:14 UTC, JimFuller-RedHat commented on docs/developer/DEVELOP.md
> +This would include events on the specific Flaw and any FlawMeta and Affect events
will remove

2024-06-12 07:14 UTC, JimFuller-RedHat commented on docs/developer/DEVELOP.md
> +We generate an audit of activity on Flaw, FlawMeta and Affect. This information is
will remove

2024-06-12 07:38 UTC, merged