remove obsoleted pghistory
RedHatProductSecurity/osidb pull request #49
Opened 2022-09-20 13:33 UTC by osoukup

and also the related pgtrigger in hope that it will kill the immortal trigger

2022-09-20 14:05 UTC, Elkasitu requested changes
This will block the migration process since one of the osidb migrations depends on a pghistory migration...

If you wanna solve it, I think we can do a migration squash and hopefully that should get rid of the dependency as the migration that added the `*event` tables and the one that removed them should cancel each other out (and thus the dependency)

2022-09-20 14:17 UTC, osoukup commented
@Elkasitu you are correct, I just encountered the error on my local. I can try to sqaush the migrations but I am not sure what it is going to do in the production/stage where they are already applied. Will try to look at the documentation.

2022-09-20 14:36 UTC, osoukup commented
@Elkasitu so (may you already know) it seems that there is n-1 compatibility recommended approach so it should be save. They advise to create the sqaushed one while preserving the old ones, do the release, remove the old ones, do the release.

2022-11-23 17:20 UTC, Elkasitu commented
This can now be merged after #79, and I would recommend doing so before starting to populate the Aurora databases (so as to not infect them with the pgtrigger virus :-))

2022-11-24 11:11 UTC, osoukup commented
@Elkasitu thank you for the reminder! I will rebase and finish this one when https://github.com/RedHatProductSecurity/osidb/pull/79 is merged.

2022-11-28 07:54 UTC, Elkasitu commented on requirements.in
> +django-pgconnection
I don't think we need this

2022-11-28 09:21 UTC, Elkasitu approved these changes
We can finally say goodbye to pghistory/pgtrigger :D

2022-11-28 09:22 UTC, osoukup commented
Finally !

2022-11-28 09:22 UTC, merged