Add switch to turn collectors on/off
RedHatProductSecurity/osidb pull request #590
Opened 2024-06-18 11:00 UTC by dmonzonis

This commit implements a way to turn off each collector using an environment variable. Turning it off means it won't be caught by celery, and therefore it won't be run automatically, although the collectors can still be run manually from a shell even if they have been turned off.

There is an environment variable for each of the collector groups: Bugzilla, Jira, Errata Tool, NVD and OSV. This means they can each be turned on/off individually.

The collectors are turned on by default.

Closes OSIDB-2884.

2024-06-18 11:58 UTC, MrMarble commented on collectors/framework/models.py
> +    emabled:    - whether the collector is to be executed as a celery
small typo
```suggestion
    enabled:    - whether the collector is to be executed as a celery
```

2024-06-18 12:03 UTC, JakubFrejlach approved these changes
Small consideration, otherwise LGTM!

2024-06-18 12:13 UTC, jobselko commented on docker-compose.yml
> +        OSV_COLLECTOR_ENABLED: ${OSV_COLLECTOR_ENABLED}
And maybe even into `docker-compose.test.yml` to disable collectors on localhost?

2024-06-18 12:15 UTC, dmonzonis commented on collectors/framework/models.py
> +    emabled:    - whether the collector is to be executed as a celery
oops

2024-06-18 15:11 UTC, dmonzonis commented on docker-compose.yml
> +        OSV_COLLECTOR_ENABLED: ${OSV_COLLECTOR_ENABLED}
@jobselko AFAIK `docker-compose.test.yml` only defines the test pods, and the celery pods are defined in `docker-compose.yml` so adding the env vars there should be enough to be able to enable/disable them in localhost

2024-06-19 07:08 UTC, osoukup requested changes
I think we need a higher granularity - on collector level, not module level. Otherwise the mechanism looks great, this is exactly what we need.

2024-06-19 07:08 UTC, osoukup commented on collectors/bzimport/constants.py
> +COLLECTOR_ENABLED = get_env("BZ_COLLECTOR_ENABLED", default="True", is_bool=True)
Could we make this on a higher level of granularity? Currently eg. on the UAT we would need the flaw collector disabled by the tracker and the metadata one enabled which is not possible with this simple approach.

2024-06-19 07:08 UTC, osoukup commented on collectors/jiraffe/tasks.py
> +from .constants import COLLECTOR_ENABLED
Here we might also get use of the switch split in some scenarios.

2024-06-19 07:08 UTC, osoukup commented on docker-compose.yml
> +        OSV_COLLECTOR_ENABLED: ${OSV_COLLECTOR_ENABLED}
I am also thinking about the OPS repo. As most of the case we want the collectors on and they are on by default we do not have to add them there. The only case I would be for adding is to disable the UAT flaw collector. When it is enable but the BBSync is disabled it results in weird situations when something may be created internally in the DB and then synced from Bugzilla once more (eg. Assembler collector duplicates).

2024-06-19 11:47 UTC, dmonzonis commented on docker-compose.yml
> +        OSV_COLLECTOR_ENABLED: ${OSV_COLLECTOR_ENABLED}
@osoukup I made a [PR](https://gitlab.corp.redhat.com/product-security/dev/osidb-ops/-/merge_requests/88) to add these variables in the ops repo

2024-06-19 13:42 UTC, osoukup approved these changes
LGTM

2024-06-19 14:12 UTC, merged