Update version to 4.1.8
RedHatProductSecurity/osidb pull request #712
Opened 2024-08-29 18:01 UTC by jsvob

see the changelog

2024-08-29 18:04 UTC, costaconrado approved these changes
LGTM.

2024-08-30 06:28 UTC, osoukup approved these changes
LGTM

2024-08-30 06:39 UTC, jobselko commented on docs/CHANGELOG.md
Should not this be a minor release? There was an API change.

2024-08-30 09:01 UTC, JakubFrejlach requested changes
Agree with @jobselko, this should be minor release 4.2.0

2024-08-30 09:01 UTC, closed without merging