env independent tests
RedHatProductSecurity/osidb pull request #719
Opened 2024-09-02 12:57 UTC by osoukup

- provide the default value for the only var which needs it in the tests and does not have it
- stop syncing the local env variables to the testrunner container to make it local-env-independent
- stop pinning constants which do not need it (mostly because the default value is the same)
- provide one forgotten env var mapping in the osidb-service container compose

2024-09-02 14:18 UTC, jobselko approved these changes

2024-09-03 05:10 UTC, JakubFrejlach requested changes
I still see the env varts in the testrunner container, despite multiple `make stop-local/make start-local` and even `make compose-down`

2024-09-03 07:10 UTC, jsvob commented on docker-compose.test.yml
> +      environment: []
```
$ podman exec -it testrunner bash
[root@b59b12fc83c6 src]# declare -p BZIMPORT_BZ_API_KEY
bash: declare: BZIMPORT_BZ_API_KEY: not found
[root@b59b12fc83c6 src]# declare -p BZIMPORT_BZ_URL
bash: declare: BZIMPORT_BZ_URL: not found
[root@b59b12fc83c6 src]# declare -p ET_URL
bash: declare: ET_URL: not found
[root@b59b12fc83c6 src]# declare -p HTTPS_PROXY
bash: declare: HTTPS_PROXY: not found
[root@b59b12fc83c6 src]# declare -p HTTPS_TASKMAN_PROXY
bash: declare: HTTPS_TASKMAN_PROXY: not found
[root@b59b12fc83c6 src]# declare -p JIRA_AUTH_TOKEN
bash: declare: JIRA_AUTH_TOKEN: not found
[root@b59b12fc83c6 src]# declare -p JIRA_TASKMAN_AUTO_SYNC_FLAW
bash: declare: JIRA_TASKMAN_AUTO_SYNC_FLAW: not found
[root@b59b12fc83c6 src]# declare -p JIRA_TASKMAN_PROJECT_KEY
bash: declare: JIRA_TASKMAN_PROJECT_KEY: not found
[root@b59b12fc83c6 src]# declare -p JIRA_TASKMAN_URL
bash: declare: JIRA_TASKMAN_URL: not found
[root@b59b12fc83c6 src]# declare -p JIRA_URL
bash: declare: JIRA_URL: not found
[root@b59b12fc83c6 src]# declare -p OSIDB_CORS_ALLOWED_ORIGINS
bash: declare: OSIDB_CORS_ALLOWED_ORIGINS: not found
[root@b59b12fc83c6 src]# declare -p OSIDB_CORS_ALLOW_HEADERS
bash: declare: OSIDB_CORS_ALLOW_HEADERS: not found
[root@b59b12fc83c6 src]# declare -p PRODUCT_DEF_URL
bash: declare: PRODUCT_DEF_URL: not found
[root@b59b12fc83c6 src]# declare -p PRODUCT_DEF_BRANCH
bash: declare: PRODUCT_DEF_BRANCH: not found
[root@b59b12fc83c6 src]# declare -p PS_CONSTANTS_URL
bash: declare: PS_CONSTANTS_URL: not found
[root@b59b12fc83c6 src]# declare -p SNIPPET_CREATION
bash: declare: SNIPPET_CREATION: not found
[root@b59b12fc83c6 src]# declare -p SNIPPET_CREATION_START
bash: declare: SNIPPET_CREATION_START: not found
[root@b59b12fc83c6 src]# 
```

Did you rebuild the image and recreate the container?

2024-09-03 07:16 UTC, JakubFrejlach commented on docker-compose.test.yml
> +      environment: []
I just recreated the container, yes, after rebuilding it works like expected but I wonder why. I thought that these env vars are only sourced upon container running and not embedded on build :thinking:

2024-09-03 07:27 UTC, jsvob approved these changes
Looks like magic to me, but it works. Based on some searching, it seems the variables are also set in the individual tests that need them, so this PR in part removes the duplicates.

2024-09-03 07:39 UTC, jsvob commented on docker-compose.test.yml
> +      environment: []
A mystery. IDK.
I found them embedded in metadata both in `.local/share/containers/storage/overlay-images/` and in `.local/share/containers/storage/overlay-containers`. Even though https://docs.docker.com/compose/environment-variables/ says "container" and not "image", https://docs.docker.com/compose/environment-variables/envvars-precedence/ does talk about "Image ENV" and IDK how exactly podman-compose works...

2024-09-03 08:15 UTC, JakubFrejlach commented on docker-compose.test.yml
> +      environment: []
whole podman-compose is kinda rigged, when we have some time in the future we should probably migrate to docker-compose.

2024-09-03 08:15 UTC, JakubFrejlach approved these changes

2024-09-03 08:30 UTC, osoukup commented on docker-compose.test.yml
> +      environment: []
@JakubFrejlach have you solved it at the end or do you still think that this PR does not work? In my case after the image rebuild the env changes are correctly reflected. The environment there looks this way
```
PYTHONUNBUFFERED=1
REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
LANG=C.utf8
which_declare=declare -f
container=oci
PIP_INDEX_URL=
PWD=/opt/app-root/src
HOME=/root
PIP_NO_CACHE_DIR=off
TERM=xterm
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LESSOPEN=||/usr/bin/lesspipe.sh %s
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
_=/usr/bin/env
```

2024-09-03 08:40 UTC, merged

2024-09-03 09:47 UTC, JakubFrejlach commented on docker-compose.test.yml
> +      environment: []
Yeah, after the image rebuild it got solved, I was just confused as I didn't know that these env vars are embeded to the image (and maybe it is a podman-compose bug).