OSIDB-3479: Allow searching for flaw components
RedHatProductSecurity/osidb pull request #750
Opened 2024-09-26 12:29 UTC by MrMarble

DjangoQL lacks suport for `ArrayField` type, so searching for flaw components was not working, neither the suggestions.

I implemented a custom field that allows searching for the components:

Some example queries and explanations:

* `components = "openssl"`:  Any flaw that has at least one component named *openssl*
* `components in ("openssl", "kernel")`: Any flaw that has at least one component named *openssl* **or** *kernel*
* `components = "openssl,kernel"`: Any flaw that has both *openssl* **and** *kernel* components
* `components = ""`: Any flaw that does not have any components
* `components != ""`: Any flaw that hast at least one component

Closes OSIDB-3479

2024-09-30 12:45 UTC, osoukup approved these changes
LGTM

2024-10-01 07:51 UTC, jobselko requested changes
Wrong section in changelog

2024-10-01 08:02 UTC, jobselko commented on osidb/filters.py
> +        return flat_list
Could this be simplified?

2024-10-01 08:14 UTC, jobselko approved these changes

2024-10-01 08:30 UTC, merged