OSIDB-3482: Remove duplicates from advanced search
RedHatProductSecurity/osidb pull request #751
Opened 2024-09-26 14:12 UTC by MrMarble

On some cases with advanced queries (specially with relations on different models) osidb is returning the same results multiple times, just needed to add a `distinct` to the query search to solve it.

For example, if a flaw has 10 affects without trackers, when searching for `affects.trackers != None` the same flaw will be returned 10 times

2024-09-30 12:23 UTC, jobselko approved these changes
LGTM, please rebase changelog

2024-09-30 12:39 UTC, osoukup approved these changes
LGTM

2024-09-30 13:07 UTC, JakubFrejlach approved these changes
LGTM!

2024-09-30 13:45 UTC, jobselko commented
FTR, I removed this PR from the merge queue as a release is currently running, and the changelog will need to be updated after the release finishes.

2024-10-01 07:50 UTC, jobselko requested changes
Wrong section in changelog

2024-10-01 08:47 UTC, jobselko approved these changes

2024-10-01 09:16 UTC, merged